### ISSUE TITLE
Safari 5.1.7 does not work

### ISSUE THREAD

**Issue by mkorganashvili** [martinaglv/jQuery-FullScreen#16]
Fullscreen does not work in Safari 5.1.7

`Element.ALLOW_KEYBOARD_INPUT` need to be removed

**Comment by chrisvfritz** [comment]
You're welcome to fork for your specific purposes, but considering the very tiny number of users on Safari 5.1.x and the fact that even Apple ceased support over 3 years ago, I don't think it's worth supporting at this point.
